'''
Facilities for logging all activity generated by the
XScore Server, including service status checks and
database manipulation.
'''

import logging

logger = logging.getLogger('xscore')
logger.setLevel(logging.DEBUG)

console = logging.StreamHandler()
console.setLevel(logging.DEBUG)
logger.addHandler(console)

import os
if os.getenv("XSCORE_LOG"):
    logfile = logging.FileHandler(os.getenv("XSCORE_LOG"))
    logfile.setLevel(logging.DEBUG)
    fmt = logging.Formatter("%(message)s - %(asctime)s")
    logfile.setFormatter(fmt)
    logger.addHandler(logfile)
